repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        files: 'mbrl'
        language_version: python3.7

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        files: 'mbrl'
        additional_dependencies: [-e, "git+git://github.com/pycqa/pyflakes.git@1911c20#egg=pyflakes"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        files: 'mbrl'
        additional_dependencies: [torch, tokenize-rt==3.2.0, types-PyYAML, types-termcolor]
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: setup.py

  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: 'mbrl'
      - id: isort
        files: 'tests'
        args: [ "--profile", "black" ]
