# @package _group_
env: "pybulletgym___InvertedPendulumMuJoCoEnv-v0"

env_cfg: 
  _target_: "pybulletgym.envs.mujoco.envs.pendulum.inverted_pendulum_env.InvertedPendulumMuJoCoEnv"

term_fn: "inverted_pendulum"

num_steps: 20000
epoch_length: 250
num_elites: 5
patience: 5
model_lr: 0.001
model_wd: 0.00005
model_batch_size: 256
validation_ratio: 0.2
freq_train_model: 250
effective_model_rollouts_per_step: 400
rollout_schedule: [1, 15, 1, 1]
num_sac_updates_per_step: 20
sac_updates_every_steps: 1
num_epochs_to_retain_sac_buffer: 1

sac_critic_lr: 0.0003
sac_actor_lr: 0.0003
sac_alpha_lr: 0.0001
sac_actor_update_frequency: 1
sac_critic_target_update_frequency: 4
sac_target_entropy: -0.05
sac_hidden_depth: 2
