# @package _group_
name: "pets"

agent:
  _target_: mbrl.planning.TrajectoryOptimizerAgent
  action_lb: ???
  action_ub: ???
  planning_horizon: 15
  optimizer_cfg: ${algorithm.optimizer}
  replan_freq: 1
  verbose: ${debug_mode}

optimizer:
  _target_: mbrl.planning.CEMOptimizer
  num_iterations: 5
  elite_ratio: 0.1
  population_size: 500
  alpha: 0.1
  lower_bound: ???
  upper_bound: ???
  return_mean_elites: true
  device: ${device}

normalize: true
target_is_delta: true
increase_val_set: true
dataset_size: ???
initial_exploration_steps: ${overrides.trial_length}
freq_train_model: 1000
learned_rewards: ${overrides.learned_rewards}

num_particles: 20
