# @package _group_
name: "pddm"
dynamics_model: gaussian_mmlp_ensemble
agent:
  _target_: mbrl.planning.TrajectoryOptimizerAgent
  action_lb: ???
  action_ub: ???
  planning_horizon: ${overrides.planning_horizon}
  optimizer_cfg: ${algorithm.optimizer}
  replan_freq: 1
  verbose: ${debug_mode}

optimizer:
  _target_: mbrl.planning.MPPIOptimizer
  batch_size: ${overrides.mppi_batch_size}
  beta: ${overrides.mppi_beta}
  planning_horizon: ${overrides.mppi_planning_horizon}
  rew_weight: ${overrides.mppi_rew_weight}
  noise_magnifier: ${overrides.mppi_noise_magnifier}
  lower_bound: ???
  upper_bound: ???
  device: ${device}

normalize: true
target_is_delta: true
initial_exploration_steps: ${overrides.trial_length}
freq_train_model: ${overrides.freq_train_model}
learned_rewards: ${overrides.learned_rewards}
